### PR TITLE
FIX negative values in random interpolator

### PR DESCRIPTION
**Pull request by acoandre**
The randomLinearInterpolator fails to parse negative values.

Allow the optional sign in the regex matcher.

### CODE REVIEW

**Comment by fgalan** [comment]
Thanks for the contribution!

It seems that lint complains (see travis report):

```
lib/interpolators/randomLinearInterpolator.js: line 109, col 121, Line is too long.
```

Could you fix it, please?

In addition, please add an entry about the fix in the CHANGES_NEXT_RELEASE file. For instance:

```
- Fix: support negative values in random interpolator
```

**Comment by acoandre** [comment]
Lint should be satisfied now and a new entry is also added to CHANGES_NEXT_RELEASE.

But I am at a complete loss as to what Travis does not like this time, though this kind of error seems to have happened before.

**Comment by fgalan** [comment]
> But I am at a complete loss as to what Travis does not like this time, though this kind of error seems to have happened before.

Sometimes some unit tests glitches. Re-run travis solve the issue, as this time.

Thanks!

**Comment by fgalan** [comment]
This is weird... I see a NOK mark in travis in the PR but if I go to the detail in travis page it seems to be ok:

imagen

Let's merge and see how it goes in master...

**Comment by fgalan** [comment]
> Let's merge and see how it goes in master...

It worked :)

imagen

**Pull request merged**
