### PR TITLE
task/compatibility_for_nodejs_12

### PR DESCRIPTION
**Pull request by cesarjorgemartinez**
Issue #76

### CODE REVIEW

**Comment by cesarjorgemartinez** [comment]
Fix https://github.com/telefonicaid/fiware-device-simulator/issues/76

**Comment by cesarjorgemartinez** [comment]
We need to generate a new release for this component because only use releases.

**Comment by fgalan** [comment]
Pending (on my side):

* .travis.yml fixes (maybe even to move to GitHub Actions)
* Dockerfile fixes

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
